### ISSUE TITLE
usage of geocoder for APIs

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/geocoder_slim#1]
Triggered by the conversation here: https://github.com/degauss-org/degauss-org.github.io/issues/7, I think this entire container might be obsolete with degauss/geocoder:3.0

In the README here, we describe how to run the container in the background and execute calls from it.  This approach is captured in https://github.com/geomarker-io/OfflineGeocodeR too. The main difference is that the ruby script outputs the geocoding results to stdout, instead of to a temporary file.  This change was also implemented in version 3.0 of degauss/geocoder, so I think we can move the instructions from here into the README of degauss/geocoder (after testing that it works the same.)

Then we can deprecate this and update https://github.com/geomarker-io/OfflineGeocodeR to use geocoder/degauss:3.0 instead of the geocoder_slim.

**Comment by erikarasnick** [comment]
I've implemented geocoder 3.0 in `OfflineGeocodeR` [here](https://github.com/geomarker-io/OfflineGeocodeR/pull/1). 

But I don't think geocoding a single address works the same for geocoder 3.0 as it did for geocoder_slim. It works if I shell in, then use `docker exec` to geocode one address, as is done in `OfflineGeocodeR`

`docker run -it -d --name gs --entrypoint /bin/bash degauss/geocoder`

then

`docker exec gs ruby geocode.rb "3333 Burnet Ave Cincinnati OH 45229"`

gives

`/var/lib/gems/2.7.0/gems/Geocoder-US-2.0.4/lib/geocoder/us/database.rb:633: warning: constant ::Fixnum is deprecated
[{"street":"Burnet Ave","zip":"45229","city":"Cincinnati","state":"OH","lat":39.141224,"lon":-84.500448,"fips_county":"39061","score":0.949,"prenum":"","number":"3333","precision":"range"}]`

**Comment by cole-brokamp** [comment]
Since we are good to merge over there, can you deprecate this repository with a README message pointing to the OfflineGeocoderR package and [this wiki post](https://github.com/degauss-org/degauss-org.github.io/wiki/Using-degauss-geocoder-as-a-geocoding-API) that I just wrote.
